plugins {
	id 'fabric-loom' version '0.5-SNAPSHOT'
	id 'maven-publish'
}

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

archivesBaseName = project.mod_id
version = project.minecraft_version + "-fabric-" + project.mod_version
group = "trackapi"

repositories {
	maven { url "https://maven.fabricmc.net/" }
	maven { url "https://maven.minecraftforge.net/" }
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	inputs.property "version", project.version
	inputs.property "minecraft_version", project.minecraft_version
	inputs.property "mod_id", project.mod_id
	inputs.property "mod_name", project.mod_name
	inputs.property "mod_description", project.mod_description
	inputs.property "mod_author", project.mod_author

	from(sourceSets.main.resources.srcDirs) {
		include "fabric.mod.json"
		expand "version": project.version,
			"minecraft_version": project.minecraft_version,
			"mod_id": project.mod_id,
			"mod_name": project.mod_name,
			"mod_description": project.mod_description,
			"mod_author": project.mod_author
	}

	from(sourceSets.main.resources.srcDirs) {
		exclude "fabric.mod.json"
	}
}

tasks.withType(JavaCompile) {
	options.encoding = "UTF-8"
}

java {
	withSourcesJar()
}

jar {
	from "LICENSE"
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifact remapJar
			artifact sourcesJar
		}
	}
	repositories {
		maven {
			url "sftp://teamopenindustry.cc:22/var/www/html/maven/"
			credentials {
				username = System.getenv("MAVENCI_USER")
				password = System.getenv("MAVENCI_PASS")
			}
		}
	}
}
