org.gradle.jvmargs=-Xmx3G

# Minecraft and Fabric Versions for 1.16.5
minecraft_version=1.16.5
yarn_mappings=1.16.5+build.10
loader_version=0.11.7
fabric_api_version=0.29.3+1.16
loom_version=0.10-SNAPSHOT

# Mod Info
mod_version=1.3
mod_id=trackapi
mod_name=Track API
mod_description=A common track interface for Minecraft
mod_author=cam72cam
